name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}

    strategy:
      fail-fast: true
      matrix:
        ruby:
          - '3.2'
          - '3.1'
          - '3.0'
          - 'jruby'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache

      - name: Run tests
        run: bundle exec rake --trace
        continue-on-error: false

  coveralls:
    name: Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake

      - name: Report coverage
        uses: coverallsapp/github-action@v2
        with:
          flag-name: ruby-3.2
          parallel: true
